title: Fajar Florist
headline: Karangan Bunga Bekasi - Fast Response 24/7
url: https://fajarflorist.com
description: Bunga papan dukacita, wedding, congratulations, hand bouquet, bunga box, standing flower. Pusat karangan bunga Bekasi. Pesan via chat WA di sini!
keywords: karangan, bunga, kembang, flower, florist, duka, suka, cita, berduka, bahagia
ogp: /assets/upload/config/ogp.jpeg
phone_number: 6285891037912
whatsapp_number: 6285891037912
whatsapp_chat: |-
  Halo kak...
  Saya mau order :

