url: https://fajarflorist.github.io
title: Fajar Florist
headline: Karangan Bunga Bekasi - Fast Response 24/7
description: Bunga papan dukacita, wedding, congratulations, hand bouquet, bunga box, standing flower. Pusat karangan bunga Bekasi. Pesan via chat WA di sini!
keywords: karangan, bunga, kembang, flower, florist, duka, suka, cita, berduka, bahagia
phone_number: 628123456789
whatsapp_number: 628123456789
whatsapp_chat: Halo%20kak...%0ASaya%20mau%20order%20
